apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/liamr03/k8s-test.git
    targetRevision: main
    path: my-monitoring-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
